# .goreleaser.yml
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X "github.com/okt-limonikas/bublik-log-viewer/constants.Version={{.Version}}"
      - -s -w -X "github.com/okt-limonikas/bublik-log-viewer/constants.Commit={{.Commit}}"
      - -s -w -X "github.com/okt-limonikas/bublik-log-viewer/constants.Date={{.Date}}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README*
      - LICENSE*
      - CHANGELOG*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# New recommended sections for version 2
report_sizes: true
source:
  enabled: true

# Adding release signing (optional but recommended)
signs:
  - cmd: gpg
    artifacts: checksum

# Adding checksum generation
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
