# .goreleaser.yml
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - binary: "blv"
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X "github.com/okt-limonikas/bublik-log-viewer/internal/constants.Version={{.Version}}"
      - -s -w -X "github.com/okt-limonikas/bublik-log-viewer/internal/constants.Commit={{.Commit}}"
      - -s -w -X "github.com/okt-limonikas/bublik-log-viewer/internal/constants.Date={{.Date}}"

archives:
  - name_template: >-
      blv_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README*
      - LICENSE*
      - CHANGELOG*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

force_token: github

# New recommended sections for version 2
report_sizes: true
source:
  enabled: true

# Adding release signing (optional but recommended)
# signs:
#   - cmd: gpg
#     artifacts: checksum

# Adding checksum generation
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
