name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Frontend
        uses: actions/checkout@v4
        with:
          repository: ts-factory/bublik-ui
          path: bublik-ui
          ref: json-logs
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: bublik-ui/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: bublik-ui
        run: pnpm install --frozen-lockfile
      
      - name: Build Frontend
        working-directory: bublik-ui
        run: pnpm run bublik-json:build

      - name: Move Frontend Build Files
        run: |
          rm -rf frontend/build
          mkdir -p frontend/build
          cp -r bublik-ui/dist/apps/bublik-logs/* frontend/build/

      - name: Set Up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: "1.22.2"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.1.0
        if: ${{ !env.ACT }}
        with:
          distribution: goreleaser
          args: release --clean
          workdir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
